### ISSUE TITLE
Non suppression de phrases dans les menus inbox, unknown et search

### ISSUE THREAD

**Issue by LiviaHaulot** [voyages-sncf-technologies/tock#1]
**Description** : Lorsque l'on est en mode tableau dans les menus inbox, unknown et search, et que sont sélectionnées des phrases à supprimer, aucune suppression n'a lieu, Les phrases sont simplement mélangées.

**Repoduction de l'anomalie** : 
- être dans le menu NLU > inbox / search / unknoxn,
- mettre l'affichage en mode tableau 
- sélectionner une phrase 

![ANO-non suppression sélection phrases](https://user-images.githubusercontent.com/39556657/72062062-58f48a00-32d7-11ea-9190-457c70fc92d6.jpg)

**Résultats** : les phrases sont mélangées mais non supprimées

![ANO-non suppression après](https://user-images.githubusercontent.com/39556657/72062069-5abe4d80-32d7-11ea-9932-e614875f4385.jpg)

**Comment by francoisno** [comment]
Solved. See https://github.com/theopenconversationkit/tock/issues/732
