### ISSUE TITLE
can't create two intents with the same name in different NLP applications

### ISSUE THREAD

**Issue by Bybeez** [voyages-sncf-technologies/tock#223]
### Steps to reproduce
1.Start the NLP stack with docker
2.Login and create a new NLP application from the "configuration" tab
3.Create a new Intent
4.Create a second NLP application
5.Create a new intent with the same name a the first one in the new application

It should create an intent with the name entered but instead it doesn't create it and display an error saying "Intent YOUR_INTENT_NAME already exists"

I'm using the compose file from the open-data-bot example with the latest tag

**Comment by vsct-jburet** [comment]
Thanks for reporting. 

We need to decide if the intent should be rebuilt from the sentences of the two applications (ie it's a "shared" intent between the two apps) or if two intents of the same name are in fact completely distinct.

The intent was designed to be shared, but I'm not so sure now, so temporarily it's forbidden to have an intent of same name.

What do you think? What is the behaviour you expect when you try to create twice an intent with same name in two apps?

**Comment by Bybeez** [comment]
I would expect them to be different, but if I'm informed that shared intents are a thing, then I'd use them for general purpose intents (ie "greetings" that don't really change between to apps). I think i could help save a lot of time just copying the same sentences for the exact same purpose.

**Comment by vsct-jburet** [comment]
We have decided to keep the "share intent" facility - they are shared in a given namespace (ie an account), so you still can have two different intents with same name in two different namespaces.

I will commit soon the changes that allow intent reuse for the same namespace in the admin interface
