### ISSUE TITLE
Can't choose connector type while creating a new Bot configuration

### ISSUE THREAD

**Issue by Bybeez** [voyages-sncf-technologies/tock#224]
##Steps to reproduce
1.Start the NLP stack with docker
2.Login and create a new bot configuration
3.Write another connector type (default:Messenger)

It should create a bot configuration with the wanted connector type but instead overwrite the choice with Messenger, and by default it displays the messenger connector configuration, and when the configuration is created, the connector type is grayed out and so I can't change it

I'm using the compose file from the open-data-bot example with the latest tag

**Comment by vsct-jburet** [comment]
Indeed the connector configuration has to be reworked. For now the workflow is:

1. Add a connector in the code (ie addSlackConnector ... )
2. Restart the bot app 
3. Refresh the admin, you should see the new connector config

So the bot configuration tab is mostly a "read" configuration (even if you can update some parameters).

The improvment of the tab is planned (I'm going to commit a roadmap in a few days). It is linked to the "bot without code" story: it will be doable soon to write a (minimal) bot using then admin interface only
