### ISSUE TITLE
Messenger rest connector not working

### ISSUE THREAD

**Issue by Bybeez** [voyages-sncf-technologies/tock#281]
Can't use the messenger rest connector in the test interface, always get a "technical error :(", tried with both already existing configurations, and fresh installs of the open-data bot and neither worked. When working with a pre-configured bot, I tested a conversation through a test plan and got the "java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [rest-your-page-id]" error. Other connectors work fine.

**Comment by vsct-jburet** [comment]
Very strange. I do not reproduce the bug at all. Can you provide an extract of  your bot_configuration collection in tock_front db? (don't forget to replace the sensible values ;) )

**Comment by Bybeez** [comment]
Here it is !
```json
{

	"_id" : "5b2119feadbe1d000532e406",
	"applicationId" : "test",
	"botId" : "paris-parking-bot",
	"namespace" : "app",
	"nlpModel" : "paris-parking-bot",
	"connectorType" : {
		"id" : "rest",
		"userInterfaceType" : "textChat"
	},
	"ownerConnectorType" : {
		"id" : "messenger",
		"userInterfaceType" : "textChat"
	},
	"name" : "test",
	"baseUrl" : "http://paris-parking-bot:8080",
	"parameters" : {
		
	},
	"manuallyModified" : true,
	"path" : "/test"
}
```

**Comment by vsct-jburet** [comment]
I do not reproduce the fact to not be able to talk to the bot via the "Test the bot" menu (it works on my side), BUT I do reproduce the test plan issue ( invalid hexadecimal error) that is now fixed in snapshot.

Please run the docker snapshot, and if the error persists, look at the admin docker image logs and report any error in it. Thanks.

**Comment by Bybeez** [comment]
The error doesn't come from the admin but from the bot : 
```
paris-parking-bot_1  | 2018-06-18T08:57:37.877 [vert.x-worker-thread-1] DEBUG fr.vsct.tock.bot.engine.BotRepository - refresh configuration BotApplicationConfiguration(applicationId=paris-parking-bot, botId=paris-parking-bot, namespace=app, nlpModel=paris-parking-bot, connectorType=rest, ownerConnectorType=messenger, name=paris-parking-bot, baseUrl=http://paris-parking-bot:8080, parameters={}, manuallyModified=true, path=/test, _id=5b277180b3cb1f000503f609)
paris-parking-bot_1  | 2018-06-18T08:57:37.877 [vert.x-worker-thread-1] ERROR fr.vsct.tock.bot.engine.BotRepository - Collection contains no element matching the predicate.
```

**Comment by vsct-jburet** [comment]
OK. The more likely is that you have an old version of the lib tock-bot-connector-messenger (or -rest) in your bot classpath. check you use the 1.1.0 (or 1.1.1-SNAPSHOT) version of tock in the bot dependencies.

You should have a file in META-INF/services/ directory in the tock-bot-connector-[messenger|rest]-[version].jar dependency
