### ISSUE TITLE
Missing script when start admin interface ?

### ISSUE THREAD

**Issue by cyrilcc** [voyages-sncf-technologies/tock#309]
Hi,

  I'm facing an issue when I try to start the admin interface.
  It seems like it misses a script in the mongo setup task.

  See my console : 

```
cyril@cyril-machine:/media/sf_DEV/NLP/tock$ docker-compose up

Starting tock_mongo_1 ... 
tock_duckling_1 is up-to-date
Starting tock_mongo_1
Starting tock_mongo_1 ... done
Starting tock_mongo2_1 ... 
Starting tock_mongo2_1 ... done
Starting tock_mongo3_1 ... 
Starting tock_mongo3_1 ... done
tock_nlp_api_1 is up-to-date
Starting tock_admin_web_1 ... 
Starting tock_admin_web_1
Starting mongo-setup ... 
Starting mongo-setup
Starting mongo-setup ... error

ERROR: for mongo-setup  Cannot start service mongo-setup: OCI runtime create failed: container_linux.go:348: starting container process causedStarting tock_admin_web_1 ... done

ERROR: for mongo-setup  Cannot start service mongo-setup: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/scripts/setup.sh\": stat /scripts/setup.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```
any idea?

**Comment by vsct-jburet** [comment]
The README of the tock-docker project is not up to date. you need to add this command to enable mongo replicaset setup:

mkdir -p scripts && curl -o scripts/setup.sh https://raw.githubusercontent.com/voyages-sncf-technologies/tock-docker/master/scripts/setup.sh && chmod +x scripts/setup.sh

I have updated the README ( https://github.com/voyages-sncf-technologies/tock-docker/commit/3a85d71a8b7a653df4966e4bc6f330320ec8f8d2). Let me know if it's ok now

**Comment by cyrilcc** [comment]
Thank you for your quick feedback!
It's ok for me now.

Actually I was following the instructions from this page : https://voyages-sncf-technologies.github.io/tock/en/getting-started/ (or https://voyages-sncf-technologies.github.io/tock/fr/pour-commencer/ )
