### ISSUE TITLE
Memory Leack

### ISSUE THREAD

**Issue by Houpert** [voyages-sncf-technologies/tock#354]
Hello,

After the server running the whole weekend, it's seem the memory leak is still here ( #350 )but leack slower this time.
The docker `tock200_build_worker_1` after running 6 days (date of the fix), the memory usage is at 1.9 Go

Docker stats :
![memoryfix](https://user-images.githubusercontent.com/6594652/48696641-c1b80900-ebe2-11e8-95de-9de82890113a.png)

and the htop (with oom data)
![htopleack](https://user-images.githubusercontent.com/6594652/48697072-ff696180-ebe3-11e8-8c92-66ad86e370c4.png)

and to finish the ps aux from the docker (Java_args looks fine)
![psauxdocker](https://user-images.githubusercontent.com/6594652/48697081-04c6ac00-ebe4-11e8-9695-8a06edf2118d.png)

Here some data of the VM if it's can help :

- uname -a : `Linux mvp-linstt 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`
- docker -v : `Docker version 18.03.1-ce, build 9ee9f40`
- docker-compose -v : `docker-compose version 1.21.2, build a133471`

I think i will try to build tock to see if this come from something else.

Thanks for the consideration !

**Comment by vsct-jburet** [comment]
Whe have just fixed a memory leak in our stanford nlp integration: https://github.com/voyages-sncf-technologies/tock-corenlp/commit/86e3035deb5de92342d331b23e1214591ca22275 Which nlp engine do you use?
If you want to avoid most of the issue, you can also pass an env properties to the worker:

`tock_test_model_enabled=false`

**Comment by Houpert** [comment]
Hello,

Sorry for not answering faster, i haven't have access to the server
Just to notify no memory leak during the 2 week.


Thank,
Best regard
