### ISSUE TITLE
define an interface for pesistence and keep MongoDB as the default implementation

### ISSUE THREAD

**Issue by yhilem** [voyages-sncf-technologies/tock#378]
Hi,
We standardized our persistence stack with Cassandra and Elasticsearch.
Is it possible to define an interface for pesistence and keep MongoDB as the default implementation?
We could thus contribute with another implementation.

Thanks
Youcef HILEM

**Comment by vsct-jburet** [comment]
You have already DAO interfaces to implement:

[NLP DAO](https://github.com/voyages-sncf-technologies/tock/tree/master/nlp/front/service/src/main/kotlin/fr/vsct/tock/nlp/front/service/storage) ->[Mongo impl](https://github.com/voyages-sncf-technologies/tock/tree/master/nlp/front/storage-mongo/src/main/kotlin/fr/vsct/tock/nlp/front/storage/mongo)

[NLP Model DAO](https://github.com/voyages-sncf-technologies/tock/tree/master/nlp/model/service/src/main/kotlin/fr/vsct/tock/nlp/model/service/storage) -> [Mongo impl](https://github.com/voyages-sncf-technologies/tock/tree/master/nlp/model/storage-mongo/src/main/kotlin/fr/vsct/tock/nlp/model/service/storage/mongo)

[Shared cache DAO](https://github.com/voyages-sncf-technologies/tock/blob/master/shared/src/main/kotlin/cache/TockCache.kt) -> [Mongo impl](https://github.com/voyages-sncf-technologies/tock/blob/master/shared/src/main/kotlin/cache/mongo/MongoCache.kt)

[Bot DAO](https://github.com/voyages-sncf-technologies/tock/tree/master/bot/engine/src/main/kotlin/fr/vsct/tock/bot) -> [Mongo Impl](https://github.com/voyages-sncf-technologies/tock/tree/master/bot/storage-mongo/src/main/kotlin/fr/vsct/tock/bot/mongo)

You have not to implement all of them. Start with the first one. After that, just use IOC ;)

Contributions are welcome :)

**Comment by yhilem** [comment]
Thank you.
Yes, we will contribute but initially with Java implementations.
