### ISSUE TITLE
Unabled to update BotApplicationConfiguration and reload connector

### ISSUE THREAD

**Issue by elebescond** [voyages-sncf-technologies/tock#384]
After connector config update it's not possible to remove conf from connectorControllerMap

So we are no able to reload the controller (unregister > register)

    object BotRepository {
    ...
      private fun removeBot(conf: BotApplicationConfiguration) {
          logger.debug { "uninstall $conf" }
          val controller = connectorControllerMap.remove(conf)
          if (controller != null) {
              if (controller is TockConnectorController) {
                  StoryConfigurationMonitor.unmonitor(controller.bot)
                  TockConnectorController.unregister(controller.connector, controller.bot, verticle)
              }
          }
      }
    ...
    }

**Comment by vsct-jburet** [comment]
I do not reproduce the bug as you can see in the test: https://github.com/voyages-sncf-technologies/tock/commit/8031ee582396bb7b7e3b6ee3c0952fbc7969f6d7#diff-26b1d90e184c966633a1f9be5ae4f2e0R166

Please provide a test case ;)
