### ISSUE TITLE
Doc: Installation de Tock

### ISSUE THREAD

**Issue by LGnord** [voyages-sncf-technologies/tock#414]
Quelques remarques à propos de la doc. Quand c'est possible, j'ai proposé une nouvelle version.
1. (docker-compose n'étant pas forcément adapté à la production): 
pourquoi? 
dans le cas d'un une base volumineuse, avec beaucoup d'utilisateurs et des requêtes gourmandes docker-compose n'est pas adapté à la production. Dans ce cas une installation manuelle des composants est recommandée.
2. Par ailleurs, il peut être souhaitable que certaines phrases soient affichées dans les logs
Dans quel cas? Qui pourrait lire des infos sensibles dans les logs?
3. Pour certaines images, ce chemin peut ne pas être présent à la racine
les quelles? que faire dans ce cas?
4. Vous pouvez cependant ajouter une encryption applicative facultative de certains champs  en base de données.
Quels champs?
5. la **loigne** de vie est localisée par défaut 
la ligne de vie est localisée par défaut

**Comment by vsct-jburet** [comment]
Merci! :)
