### ISSUE TITLE
[Twitter Connector] Add media (GIF, Image and video) for Direct Message API

### ISSUE THREAD

**Issue by auroredea** [voyages-sncf-technologies/tock#425]
Ability to send a direct message with twitter API and upload attached medias, such as images, GIFs or videos, adding them on direct message.

More information at : https://developer.twitter.com/en/docs/direct-messages/message-attachments/overview

**Comment by vsct-jburet** [comment]
fixed by https://github.com/voyages-sncf-technologies/tock/commit/2ae00f7cb941eaa3731b70d9ca3b0d1b6253783e
