### ISSUE TITLE
kmongo 3.10.2-SNAPSHOT has broken classes path

### ISSUE THREAD

**Issue by mfu-aroche** [voyages-sncf-technologies/tock#483]
Maven ne parvient pas à récupérer kmongo en version 3.10.2-SNAPSHOT (Failed to download from `https://jcenter.bintray.com/org/litote/kmongo/.../3.10.2-SNAPSHOT`) et donc ne peut pas build le projet.

> Project Structure - IntelliJ IDEA
> - Library `Maven: org.litote.kmongo:kmongo-async:3.10.2-SNAPSHOT` has broken classes path:   `C:\Users\Alexis\.m2\repository\org\litote\kmongo\kmongo-async\3.10.2-SNAPSHOT\kmongo-async-3.10.2-SNAPSHOT.jar` [Fix]
> - Library `Maven: org.litote.kmongo:kmongo-flapdoodle:3.10.2-SNAPSHOT` has broken classes path:   `C:\Users\Alexis\.m2\repository\org\litote\kmongo\kmongo-flapdoodle\3.10.2-SNAPSHOT\kmongo-flapdoodle-3.10.2-SNAPSHOT.jar` [Fix]
> - Library `Maven: org.litote.kmongo:kmongo-id-jackson:3.10.2-SNAPSHOT` has broken classes path:   `C:\Users\Alexis\.m2\repository\org\litote\kmongo\kmongo-id-jackson\3.10.2-SNAPSHOT\kmongo-id-jackson-3.10.2-SNAPSHOT.jar` [Fix]
> - Library `Maven: org.litote.kmongo:kmongo:3.10.2-SNAPSHOT` has broken classes path:   `C:\Users\Alexis\.m2\repository\org\litote\kmongo\kmongo\3.10.2-SNAPSHOT\kmongo-3.10.2-SNAPSHOT.jar` [Fix]

Est-ce qu'il me manque le bon repository pour télécharger cette version, ou il faut rétrograder à la version 3.10.1 ?

**Comment by vsct-jburet** [comment]
En effet il faut rajouter ce repository dans la liste des repository

 ```
<repository>
            <id>maven-snapshots</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```
