### ISSUE TITLE
Gitter is very hard to find

### ISSUE THREAD

**Issue by boucman** [voyages-sncf-technologies/tock#555]
Hello
I am discovering the project and there is very little help about the community aspect of the project.
the page at https://voyages-sncf-technologies.github.io/tock/en/contribute/ does not document any way to communicate and the only way I could find to contact the community was via gitter, and only because of a small badge on the top of README.md

I'm not sure how, but it is probably usefull to have something a little more visible on how to contact you 

Cheers
Jérémy

**Comment by francoisno** [comment]
Hello,
Thanks @boucman for the relevant issue.
I'll push something (probably tomorrow) to make the Gitter more visible in the current pages. BTW a new version of the documentation with more info, guides, etc. should be released in september.
Thanks again and don't hesitate to PR or continue leaving comments/issues to improve TOCK, in particular when the new documentation is available!

**Comment by boucman** [comment]
sure thing, thx

**Comment by boucman** [comment]
is that new documenation available in an unmerged pull-request or a branch somewhere ?

**Comment by francoisno** [comment]
@boucman I should be able to push a draft for the new documentation (French+English) on a branch next week, for reviews/comments/improvements.
