### ISSUE TITLE
Missing README in the connector-teams folder

### ISSUE THREAD

**Issue by albandewilde** [voyages-sncf-technologies/tock#581]
Hi, I try to make a bot using the Teams connector but there is no README file, can you publish it even if it's not finish writing ?

**Comment by sebabarre** [comment]
Hello, i will commit one during the day

**Comment by vsct-jburet** [comment]
@albandewilde see https://github.com/voyages-sncf-technologies/tock/tree/master/bot/connector-teams 
Please report any issue
