### ISSUE TITLE
Désactivation filtre après update story

### ISSUE THREAD

**Issue by LiviaHaulot** [voyages-sncf-technologies/tock#6]
Bonjour,

Dans les menus Search Stories, 
Si 
1. on filtre par une recherche texte libre.
2. On modifier une phrase ou une story
3. le filtre se désactive (il apparaît toujours mais tous les storys sont réaffichés)

**Comment by francoisno** [comment]
Merge request to review : https://github.com/theopenconversationkit/tock/pull/778

**Comment by francoisno** [comment]
Moved to https://github.com/theopenconversationkit/tock/issues/785
