### ISSUE TITLE
Demande evolution : filtrer le menu NLU > Inbox

### ISSUE THREAD

**Issue by LiviaHaulot** [voyages-sncf-technologies/tock#7]
Bonjour,

Nous aurions le besoin de filtrer le menu NLU > inbox avec des paramètres tels que l'intent, la date d'émission et la probabilité de certitude afin de faciliter notre travail de requalification. 

Cela serait-il possible ?

**Comment by francoisno** [comment]
Moved to https://github.com/theopenconversationkit/tock/issues/784
