### ISSUE TITLE
menu NLU > Search faire un dump de phrase coché

### ISSUE THREAD

**Issue by LiviaHaulot** [voyages-sncf-technologies/tock#8]
Bonjour,

En voulant faire un dump de phrases cochées (j'avais coché un certain nombre de phrase grâce à la visualisation tableau) je me suis aperçue que lorsque je faisais un "dump de la sélection en compte", ma sélection n'avait pas été prise en compte. 
Peut-on faire des dumps de phrases cochées dans le search ?

**Comment by francoisno** [comment]
Moved to https://github.com/theopenconversationkit/tock/issues/781
