### ISSUE TITLE
Upload de Dump de story recliquer sur les intents

### ISSUE THREAD

**Issue by LiviaHaulot** [voyages-sncf-technologies/tock#9]
Bonjour,

Quand nous faisons un upload de  dump de story nous sommes obligés de recliquer sur tous les intents des Actions.

Bien cordialement,

Livia Haulot

**Comment by francoisno** [comment]
Probablement un doublon de https://github.com/theopenconversationkit/tock/issues/768

**Comment by francoisno** [comment]
Moved to https://github.com/theopenconversationkit/tock/issues/783
